name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/SeniorDotNetPractice.Api/SeniorDotNetPractice.Api.csproj

      - name: Build
        run: dotnet build src/SeniorDotNetPractice.Api/SeniorDotNetPractice.Api.csproj --no-restore --configuration Release

      - name: Build Docker image
        run: docker build -t senior-dotnet-practice:${{ github.sha }} src/SeniorDotNetPractice.Api
